### ISSUE TITLE
gulpfile.js file is not ready for Gulp 4

### ISSUE THREAD

**Issue by freimuth82** [DEEP-IMPACT-AG/staticweb-build#4]
Since the change to gulp 4 I am not able to run this project any more simply by only cloning it and running "npm install", because the syntax of the gulpfile has changed. I get this error:
```
gulp build-dev

assert.js:60
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (c:\Projekte\NodeJS\staticwebsitetemplate\node_modules\undertaker\lib\set-task.js:10:3)
    at Gulp.task (c:\Projekte\NodeJS\staticwebsitetemplate\node_modules\undertaker\lib\task.js:13:8)
    at Object.<anonymous> (c:\Projekte\NodeJS\staticwebsitetemplate\gulpfile.js:64:6)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)

```
If I jump back to gulp 3.9.1 it still works.

**Comment by luangjokaj** [comment]
I'm planning to re-write the build using Gulp 4. Maybe also brand the boilerplate with a name and a better documentation, depending on the time I have available.

**Comment by luangjokaj** [comment]
@freimuth82 I just pushed an update for Gulp 4. Try to pull the latest changes, now it should work!
